"use strict";
exports.ESTADOS = [
    { id: 1, nome: 'Acre', uf: 'AC', isAtivo: true },
    { id: 2, nome: 'Alagoas', uf: 'AL', isAtivo: true },
    { id: 3, nome: 'Amazonas', uf: 'AM', isAtivo: true },
    { id: 4, nome: 'Amapá', uf: 'AP', isAtivo: true },
    { id: 5, nome: 'Bahia', uf: 'BA', isAtivo: true },
    { id: 6, nome: 'Ceará', uf: 'CE', isAtivo: true },
    { id: 7, nome: 'Distrito Federal', uf: 'DF', isAtivo: true },
    { id: 8, nome: 'Espírito Santo', uf: 'ES', isAtivo: true },
    { id: 9, nome: 'Goiás', uf: 'GO', isAtivo: true },
    { id: 10, nome: 'Maranhão', uf: 'MA', isAtivo: true },
    { id: 11, nome: 'Minas Gerais', uf: 'MG', isAtivo: true },
    { id: 12, nome: 'Mato Grosso do Sul', uf: 'MS', isAtivo: true },
    { id: 13, nome: 'Mato Grosso', uf: 'MT', isAtivo: true },
    { id: 14, nome: 'Pará', uf: 'PA', isAtivo: true },
    { id: 15, nome: 'Paraíba', uf: 'PB', isAtivo: true },
    { id: 16, nome: 'Pernambuco', uf: 'PE', isAtivo: true },
    { id: 17, nome: 'Piauí', uf: 'PI', isAtivo: true },
    { id: 18, nome: 'Paraná', uf: 'PR', isAtivo: true },
    { id: 19, nome: 'Rio de Janeiro', uf: 'RJ', isAtivo: true },
    { id: 20, nome: 'Rio Grande do Norte', uf: 'RN', isAtivo: true },
    { id: 21, nome: 'Rondônia', uf: 'RO', isAtivo: true },
    { id: 22, nome: 'Roraima', uf: 'RR', isAtivo: true },
    { id: 23, nome: 'Rio Grande do Sul', uf: 'RS', isAtivo: true },
    { id: 24, nome: 'Santa Catarina', uf: 'SC', isAtivo: true },
    { id: 25, nome: 'Sergipe', uf: 'SE', isAtivo: true },
    { id: 26, nome: 'São Paulo', uf: 'SP', isAtivo: true },
    { id: 27, nome: 'Tocantins', uf: 'TO', isAtivo: true }
];
//# sourceMappingURL=estados-mock.js.map